# Generated by Django 5.0.7 on 2024-07-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aadhar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_no', models.IntegerField(unique=True)),
                ('created_data', models.DateTimeField()),
                ('created_by', models.CharField(max_length=50)),
            ],
        ),
    ]
